name: Rust
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
# Disabled until I can find a suitable way to run this with github actions
#  test:
#    name: cargo test
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      - name: Install deps
#        uses: awalsh128/cache-apt-pkgs-action@latest
#        with:
#          packages: libxrandr-dev
#      - name: Install the toolchain
#        uses: dtolnay/rust-toolchain@stable
#      - name: Run tests
#        run: cargo test --all-features

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --check
  
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libxrandr-dev
      - name: Install the toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Linting
        run: cargo clippy --all-features -- -D warnings
